- src/main/resources/application.properties
- src/main/resources/application.yml
> DB 설정 및 yml로 설정파일 변경

- .github/workflows/main.yml
- src/test/java/com/project/food_ordering_service/FoodOrderingServiceApplicationTests.java
- src/test/resources/application.yml
> [#7] main 브랜치나 feature 브랜치에 push할 경우 자동으로 build 되게 워크플로우 작성
> CI 중 ApplicationTests > contextLoads() FAILED 에러가 생겨 @SpringBootTest 애노테이션에 classes 속성을 추가하였습니다!
> Github Actions 적용

- src/main/java/com/project/food_ordering_service/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/project/food_ordering_service/global/api/config/RestClientConfig.java
- src/main/java/com/project/food_ordering_service/global/kakaoRestApi/KakaoMapApi.java
- src/main/java/com/project/food_ordering_service/global/kakaoRestApi/dto/Documents.java
- src/main/java/com/project/food_ordering_service/global/kakaoRestApi/dto/Meta.java
- src/main/java/com/project/food_ordering_service/global/kakaoRestApi/dto/RequestKakao.java
- src/main/java/com/project/food_ordering_service/global/kakaoRestApi/dto/RequsetKakao.java
- src/main/java/com/project/food_ordering_service/global/kakaoRestApi/dto/ResponseKakaoApi.java
- src/main/java/com/project/food_ordering_service/global/kakaoRestApi/dto/SameName.java
> [#13 ] 카카오 공용 api 이용해서 주변 음식점 리스트 불러오기 api 개발
>
> 주변 음식점 불러오기 API 추가

- build.gradle
- src/main/java/com/project/food_ordering_service/domain/user/controller/LoginController.java
- src/main/java/com/project/food_ordering_service/domain/user/controller/UserController.java
- src/main/java/com/project/food_ordering_service/domain/user/dto/LoginRequest.java
- src/main/java/com/project/food_ordering_service/domain/user/dto/LoginResponse.java
- src/main/java/com/project/food_ordering_service/domain/user/dto/UserSaveRequest.java
- src/main/java/com/project/food_ordering_service/domain/user/exception/UserNotFoundException.java
- src/main/java/com/project/food_ordering_service/domain/user/repository/UserRepository.java
- src/main/java/com/project/food_ordering_service/domain/user/service/UserService.java
- src/main/java/com/project/food_ordering_service/global/config/SecurityConfiguration.java
- src/test/java/com/project/food_ordering_service/domain/user/controller/UserControllerTest.java
- src/test/java/com/project/food_ordering_service/domain/user/service/UserServiceTest.java
>[#17] 스프링 시큐리티 적용 및 로그인 API를 구현하였습니다. 기존 회원가입 요청 dto에 password 필드가 빠졌던 것을 추가하고 테스트 코드를 수정하였습니다. 컨트롤러 레이어에도 단위 테스트를 적용하였습니다.
> 토큰 구현 시 기존의 LoginController는 AuthController로 바꿀 예정입니다. 도메인형 패키지 구조에 따라 로그인은 패키지를 분리하는게 맞지만, 추후 JWT 토큰 구현시에 패키지를 분리할 예정입니다!
> 스프링 시큐리티 적용 및 로그인 API 구현

- src/test/java/com/project/food_ordering_service/domain/restaurant/controller/RestaurantControllerTest.java
> [#23 ] 카카오 api 음식점 불러오기 테스트 코드 추가
>단위 테스트를 이용해서 테스트 코드를 작성했습니다
> 카카오api 테스트 코드 추가

- src/main/java/com/project/food_ordering_service/global/api/KakaoMapApi.java
- src/main/java/com/project/food_ordering_service/global/dto/request/KakaoMapApiRequest.java
- src/main/java/com/project/food_ordering_service/global/dto/response/Documents.java
- src/main/java/com/project/food_ordering_service/global/dto/response/Meta.java
- src/test/java/com/project/food_ordering_service/global/api/KakaoMapApiTest.java
> 카카오 api 기능 테스트 코드 작성
> @RestClientTest 어노테이션을 사용해서  외부 API 호출 Mocking 테스트를 구현했습니다
> 카카오 외부 api 테스트 코드작성

- src/main/java/com/project/food_ordering_service/domain/auth/controller/AuthController.java
- src/main/java/com/project/food_ordering_service/domain/auth/exception/UnacceptedAuthrizationException.java
- src/main/java/com/project/food_ordering_service/domain/auth/repository/AuthRepository.java
- src/main/java/com/project/food_ordering_service/domain/auth/service/AuthService.java
- src/main/java/com/project/food_ordering_service/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/project/food_ordering_service/global/api/KakaoMapApi.java
- src/main/java/com/project/food_ordering_service/global/config/SecurityConfiguration.java
- src/main/java/com/project/food_ordering_service/global/utils/jwt/JwtAuthentication.java
- src/main/java/com/project/food_ordering_service/global/utils/jwt/JwtAuthenticationToken.java
- src/main/resources/application.yml
- src/test/java/com/project/food_ordering_service/domain/auth/controller/AuthControllerTest.java
- src/test/java/com/project/food_ordering_service/domain/user/controller/UserControllerTest.java
- src/test/java/com/project/food_ordering_service/domain/utils/TestUtil.java
- src/test/resources/application-test.yml
> [#22] 토큰을 재발급 받는 로직을 구현하였습니다.
> 기존 AuthController에 대해 테스트 코드를 작성하였습니다.
> JWT 토큰 재발급 기능 구현 

- .github/workflows/main.yml
- src/main/java/com/project/food_ordering_service/global/api/KakaoMapApi.java
- src/main/resources/application.yml
- src/test/resources/application-test.yml
> [#31] CI 시 카카오 맵 키를 환경변수로 받도록 설정하였습니다.
>
> 카카오 맵 API 키를 secrets로 받도록 변경

- build.gradle
- src/main/java/com/project/food_ordering_service/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/project/food_ordering_service/global/config/SecurityConfiguration.java
- src/main/java/com/project/food_ordering_service/global/config/SwaggerConfig.java
> #34  스웨거 라이브러리를 추가해서 api 명세서 작성 했습니다
> http://localhost:8080/swagger-ui/index.html
> Swagger api 명세서 작성

- build.gradle
- src/main/java/com/project/food_ordering_service/domain/order/controller/OrderController.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderRequest.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderResponse.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/Order.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/OrderStatus.java
- src/main/java/com/project/food_ordering_service/domain/order/repository/OrderRepository.java
- src/main/java/com/project/food_ordering_service/domain/order/service/OrderService.java
- src/main/java/com/project/food_ordering_service/global/dto/request/KakaoMapApiRequest.java
- src/main/java/com/project/food_ordering_service/global/utils/jwt/JwtUtil.java
- src/test/java/com/project/food_ordering_service/domain/auth/controller/AuthControllerTest.java
- src/test/java/com/project/food_ordering_service/domain/order/service/OrderServiceTest.java
- src/test/java/com/project/food_ordering_service/domain/utils/TestUtil.java
> [#26] 주문 기능을 구현하고 테스트 코드를 작성하였습니다.
>
> 주문하기 기능 구현 및 테스트 코드 작성

- Dockerfile
- build.gradle
- docker-compose.yml
- src/main/resources/application.yml
> 도커엔진을 사용해서 컨테이너 환경을 구축했습니다
>
> Docker container 추가

- src/main/java/com/project/food_ordering_service/domain/order/controller/OrderController.java
- src/main/java/com/project/food_ordering_service/domain/order/repository/OrderRepository.java
- src/main/java/com/project/food_ordering_service/domain/order/service/OrderService.java
> [#39] 주문에 대해 페이징을 적용하였습니다.
> getOrders()는 최근 주문부터 가져오고, getOrdersByUser()는 특정 사용자의 주문중에서 최근에 생성된 주문부터 가져옵니다.
> 주문 페이징 기능 구현 및 테스트

- src/main/java/com/project/food_ordering_service/domain/restaurant/entity/Restaurant.java
- src/main/java/com/project/food_ordering_service/domain/restaurant/repository/RestaurantRepository.java
> Restaurant Entity 추가 

- src/main/java/com/project/food_ordering_service/domain/order/controller/OrderController.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderRequest.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderResponse.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/Order.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/OrderStatus.java
- src/main/java/com/project/food_ordering_service/domain/order/service/OrderService.java
- src/main/java/com/project/food_ordering_service/domain/restaurant/dto/RestaurantRequest.java
- src/main/java/com/project/food_ordering_service/domain/restaurant/dto/RestaurantResponse.java
- src/main/java/com/project/food_ordering_service/domain/restaurant/repository/RestaurantRepository.java
- src/test/java/com/project/food_ordering_service/domain/order/service/OrderServiceTest.java
> #43 
레스토랑 정보를 저장 하기위해서 Order 수정 했습니다
>
> 음식 주문하기 수정

- src/main/java/com/project/food_ordering_service/domain/order/controller/OrderController.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderResponse.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderStateRequest.java
- src/main/java/com/project/food_ordering_service/domain/order/service/OrderService.java
- src/test/java/com/project/food_ordering_service/domain/order/service/OrderServiceTest.java
> 기존 {orderId}/delivery  - > /{orderId}/state 주문 상태만 변경하기 때문에 URL 주소 변경
메서드 @PatchMapping  부분 업데이트로 POST  -> PatchMapping 변경
>
> requestDelivery 수정

- .github/workflows/jacoco.yml
- .github/workflows/main.yml
- src/main/java/com/project/food_ordering_service/global/api/KakaoMapApi.java
- src/test/java/com/project/food_ordering_service/global/api/KakaoMapApiTest.java
> #59 
restClient 사용해서 외부 API 요청 
Test code 작성 완료
>
> 주소 좌표 변환 기능 추가

- build.gradle
- lombok.config
> jacoco 설정 변경

- src/main/java/com/project/food_ordering_service/domain/delivery/controller/DeliveryController.java
- src/main/java/com/project/food_ordering_service/domain/delivery/dto/DeliveryRequest.java
- src/main/java/com/project/food_ordering_service/domain/delivery/dto/DeliveryResponse.java
- src/main/java/com/project/food_ordering_service/domain/delivery/dto/DeliveryStatusRequest.java
- src/main/java/com/project/food_ordering_service/domain/delivery/entity/Delivery.java
- src/main/java/com/project/food_ordering_service/domain/delivery/exception/DeliveryNotFoundException.java
- src/main/java/com/project/food_ordering_service/domain/delivery/repository/DeliveryRepository.java
- src/main/java/com/project/food_ordering_service/domain/delivery/service/DeliveryService.java
- src/main/java/com/project/food_ordering_service/domain/order/controller/OrderController.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderResponse.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/Order.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/OrderStatus.java
- src/main/java/com/project/food_ordering_service/domain/order/service/OrderService.java
- src/main/java/com/project/food_ordering_service/domain/user/entity/Role.java
- src/main/java/com/project/food_ordering_service/global/dto/response/KakaoMapApiResponse.java
- src/main/java/com/project/food_ordering_service/global/dto/response/Meta.java
- src/test/java/com/project/food_ordering_service/domain/order/service/OrderServiceTest.java
> 배달조회 및 수락 기능을 구현하였습니다. 배달원만 배달 수락이 가능합니다. 
> 기능 구현 완료 후 테스트 코드 보충할 예정입니다! 주문 상태 enum 클래스에 변경이 있어 OrderService의 코드도 같이 수정하였습니다!
> 배달 조회 및 수락 기능 구현 

- src/main/java/com/project/food_ordering_service/domain/delivery/controller/DeliveryController.java
- src/main/java/com/project/food_ordering_service/domain/delivery/service/DeliveryService.java
- src/test/java/com/project/food_ordering_service/domain/delivery/controller/DeliveryControllerTest.java
- src/test/java/com/project/food_ordering_service/domain/delivery/service/DeliveryServiceTest.java
> 배달 취소 기능을 개발합니다. 배달 취소 시 RECEIVED에서 DELIVERY_REQUESTED로 상태가 변경되게끔 구현하였습니다. 배달 취소를 위해 우선 상태가 RECEIVED인지 검증하는 로직을 추가하였습니다!
> @RudySeo PATCH랑 DELETE에 대해 고민하였습니다! DELETE는 보통 리소스를 삭제할 때 사용하고 배달 취소는 리소스 자체를 삭제하는 것이 아닌 배달 상태 변경을 한다는 의미에서 PATCH가 더 적절할 것 같다는 생각이 드는데 어떻게 생각하시나요??
> 배달 취소 기능 개발 및 테스트 코드 작성 

- src/main/java/com/project/food_ordering_service/domain/order/controller/OrderController.java
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderStateRequest.java
- src/main/java/com/project/food_ordering_service/domain/order/service/OrderService.java
- src/main/java/com/project/food_ordering_service/global/utils/sse/controller/SseController.java
- src/main/java/com/project/food_ordering_service/global/utils/sse/repository/SseRepository.java
- src/main/java/com/project/food_ordering_service/global/utils/sse/service/SseService.java
- src/test/java/com/project/food_ordering_service/domain/order/service/OrderServiceTest.java
> SSE 사용해서 상태가 변경된 주문 대기 리스트를  즉시 업데이트 했습니다
#73 
>
> SSE 이벤트 사용

- build.gradle
- src/main/java/com/project/food_ordering_service/global/annotaion/DistributedLock.java
- src/main/java/com/project/food_ordering_service/global/aop/DistributedLockAop.java
- src/main/java/com/project/food_ordering_service/global/config/RedissonConfig.java
- src/main/java/com/project/food_ordering_service/global/distributedLock/AopTransactionExecutor.java
- src/main/java/com/project/food_ordering_service/global/distributedLock/DynamicValueParser.java
- src/main/resources/application.yml
> AOP 레디스 분산락 추가

- .github/workflows/jacoco.yml
- .github/workflows/main.yml
- src/main/java/com/project/food_ordering_service/domain/order/dto/OrderRequest.java
- src/main/java/com/project/food_ordering_service/domain/restaurant/dto/RestaurantRequest.java
- src/main/java/com/project/food_ordering_service/domain/restaurant/dto/RestaurantResponse.java
- src/main/java/com/project/food_ordering_service/domain/user/dto/UserSaveRequest.java
- src/test/resources/application-test.yml
- src/test/resources/application.yml
> 동시성 문제 테스트

- src/main/java/com/project/food_ordering_service/domain/delivery/entity/Delivery.java
- src/main/java/com/project/food_ordering_service/domain/delivery/repository/DeliveryRepository.java
- src/main/java/com/project/food_ordering_service/domain/delivery/service/DeliveryService.java
- src/main/java/com/project/food_ordering_service/domain/user/entity/User.java
> #83  연관관계 수정 
주문상태 체크 쿼리 추가
>
> 연관 관계 오류 수정

- src/main/java/com/project/food_ordering_service/domain/delivery/entity/Delivery.java
- src/main/java/com/project/food_ordering_service/domain/delivery/exception/DeliverArgumentException.java
- src/main/java/com/project/food_ordering_service/domain/delivery/service/DeliveryService.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/Order.java
> 커스텀 예외처리 수정

- .github/workflows/main.yml
- src/main/java/com/project/food_ordering_service/domain/delivery/controller/DeliveryController.java
- src/main/java/com/project/food_ordering_service/domain/delivery/entity/Delivery.java
- src/main/java/com/project/food_ordering_service/domain/delivery/repository/DeliveryRepository.java
- src/main/java/com/project/food_ordering_service/domain/delivery/service/DeliveryService.java
- src/main/java/com/project/food_ordering_service/domain/order/entity/Order.java
- src/main/java/com/project/food_ordering_service/domain/user/entity/User.java
- src/test/java/com/project/food_ordering_service/domain/delivery/controller/DeliveryControllerTest.java
> #86 
API 주소 변경
기존에 사용안하는 주문ID 제거
주석처리 제거
코드컨벤션 카멜케이스 유지를 위해서 메서드 이름변경
>
> 컨트롤러 api 변경 코드 수정

- src/main/resources/application.yml
> redis를 캐시 저장소로 사용하도록 설정 파일을 수정했었는데 캐시 기능 PR시에 변경된 yml 파일에 대해 로컬에서만 테스트를 하고 commit을 하지 않아 누락된 부분을 commit합니다.
>
> refactor: 캐시 관련 설정 파일 변경
